services:
    ControleOnline\:
        resource: "../../src/*"
        exclude: "../src/{DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}"
    ControleOnline\Repository\:
        resource: "../../src/Repository"
        tags: ["doctrine.repository_service"]
        arguments:
            $registry: "@doctrine"
            $encoder:  "@security.password_encoder"
