api_platform:
    mapping:
        paths:
            [
                "%kernel.project_dir%/vendor/controleonline/users/src/Entity",
                "%kernel.project_dir%/vendor/controleonline/users/Resource",
            ]
    
