imports:
    - { resource: "./services/services.yaml" }
    - { resource: "./routes/annotation.yaml" }
    - { resource: "./packages/api_platform.yaml" }
    - { resource: "./packages/doctrine.yaml" }
    