name: Pull Request Checks

on:
  pull_request:
  push:
    branches:
      - task-5

jobs:
  users-module:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Validate composer files
        run: composer validate --no-check-publish

      - name: Install test dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit
